kind = "web"
previewPath = "/"
title = "Online Examination Management System"
version = "1.0.0"
id = "artifacts/oems"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24560

[services.development]
run = "pnpm --filter @workspace/oems run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/oems", "run", "build" ]
publicDir = "artifacts/oems/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24560"
BASE_PATH = "/"
