import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import departmentsRouter from "./departments";
import coursesRouter from "./courses";
import classesRouter from "./classes";
import questionsRouter from "./questions";
import examsRouter from "./exams";
import enrollmentsRouter from "./enrollments";
import attemptsRouter from "./attempts";
import resultsRouter from "./results";
import analyticsRouter from "./analytics";
import proctoringRouter from "./proctoring";
import liveSessionsRouter from "./live-sessions";
import materialsRouter from "./materials";
import assignmentsRouter from "./assignments";
import announcementsRouter from "./announcements";
import gradebookRouter from "./gradebook";
import myGradesRouter from "./my-grades";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(departmentsRouter);
router.use(coursesRouter);
router.use(classesRouter);
router.use(questionsRouter);
router.use(examsRouter);
router.use(enrollmentsRouter);
router.use(attemptsRouter);
router.use(resultsRouter);
router.use(analyticsRouter);
router.use(proctoringRouter);
router.use(liveSessionsRouter);
router.use(materialsRouter);
router.use(assignmentsRouter);
router.use(announcementsRouter);
router.use(gradebookRouter);
router.use(myGradesRouter);

export default router;
