[[pages]]
path = "/"
screenshotTimestamp = "2026-06-29T18:48:56Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/476ade07-6ca9-4237-843e-ef915fed798e/0bf0e373-7d4f-4221-b4df-a4d258275101/YYu5emt"

[[pages]]
path = "/student"
screenshotTimestamp = "2026-06-29T18:49:15Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/476ade07-6ca9-4237-843e-ef915fed798e/0bf0e373-7d4f-4221-b4df-a4d258275101/awD6jhi"

[[pages]]
path = "/login"
screenshotTimestamp = "2026-06-30T10:13:37Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/476ade07-6ca9-4237-843e-ef915fed798e/0bf0e373-7d4f-4221-b4df-a4d258275101/Z7ZTNk4"

[[pages]]
path = "/signup"
screenshotTimestamp = "2026-06-30T07:34:47Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/476ade07-6ca9-4237-843e-ef915fed798e/0bf0e373-7d4f-4221-b4df-a4d258275101/8Y9krDd"

[[pages]]
path = "/forgot-password"
screenshotTimestamp = "2026-06-30T09:38:24Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/476ade07-6ca9-4237-843e-ef915fed798e/0bf0e373-7d4f-4221-b4df-a4d258275101/uxj6LtP"

[[pages]]
path = "/reset-password"
screenshotTimestamp = "2026-06-30T09:38:26Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/476ade07-6ca9-4237-843e-ef915fed798e/0bf0e373-7d4f-4221-b4df-a4d258275101/efwQl04"

[[pages]]
path = "/student/profile"
screenshotTimestamp = "2026-06-30T09:42:11Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/476ade07-6ca9-4237-843e-ef915fed798e/0bf0e373-7d4f-4221-b4df-a4d258275101/kGObIkK"

[[pages]]
path = "/lecturer/profile"
screenshotTimestamp = "2026-06-30T10:03:10Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/476ade07-6ca9-4237-843e-ef915fed798e/0bf0e373-7d4f-4221-b4df-a4d258275101/anVHjj0"

[[pages]]
path = "/student/grades"
screenshotTimestamp = "2026-06-30T10:21:11Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/476ade07-6ca9-4237-843e-ef915fed798e/0bf0e373-7d4f-4221-b4df-a4d258275101/ODbpUpX"
